### ISSUE TITLE
Could not pass event EntityDeathEvent

### ISSUE THREAD

**Issue by artworldov** [JustEli/Coins#43]
**Describe the bug**
When I kill a passive mob, the error appears in console, and if passiveDrop setting is enabled, coins don't drop

**To Reproduce**
1. Kill a passive mob
2. Error appears and coin doesn't drop

**Error**

```
Could not pass event EntityDeathEvent to Coins v1.10.3
java.lang.NoClassDefFoundError: org/bukkit/entity/Boss
	at me.justeli.coins.api.IsEntity.hostile(IsEntity.java:14) ~[?:?]
	at me.justeli.coins.events.DropCoin.entityDeath(DropCoin.java:97) ~[?:?]
	at me.justeli.coins.events.DropCoin.onEntityDeath(DropCoin.java:52) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor449.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[minecraft_server.jar:git-Paper-1618]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[minecraft_server.jar:git-Paper-1618]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Paper-1618]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[minecraft_server.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:397) ~[minecraft_server.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.EntityLiving.die(EntityLiving.java:1148) ~[minecraft_server.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.EntityPig.die(EntityPig.java:136) ~[minecraft_server.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:983) ~[minecraft_server.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.EntityHuman.attack(EntityHuman.java:1028) ~[minecraft_server.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.EntityPlayer.attack(EntityPlayer.java:1397) ~[minecraft_server.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1724) ~[minecraft_server.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[minecraft_server.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[minecraft_server.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[minecraft_server.jar:git-Paper-1618]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_292]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_292]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[minecraft_server.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[minecraft_server.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[minecraft_server.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[minecraft_server.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[minecraft_server.jar:git-Paper-1618]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.ClassNotFoundException: org.bukkit.entity.Boss
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:109) ~[minecraft_server.jar:git-Paper-1618]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[minecraft_server.jar:git-Paper-1618]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_292]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_292]
	... 26 more
```

**Additional context**
Server version: PaperMC 1.12.2 (git-Paper-1618)
Plugin version: 1.10.3

Btw, in 1.10.1 all works good

**Comment by JustEli** [comment]
fixed in 1.10.4
