### ISSUE TITLE
Coins not works with MythicMobs

### ISSUE THREAD

**Issue by Poweringg** [JustEli/Coins#52]
**Describe the bug**
Coins wont works with latest MythicMobs version, problably they changed api?

**To Reproduce**
1 download latest free version of mythicMobs - https://mythiccraft.io/index.php?pages/official-mythicmobs-download/&version=5.0.1
2 download latest version of Coins plugin - https://www.spigotmc.org/resources/coins.33382/
3 put together inside plugins folder.. error

**Expected behavior**
No error and coins work with MM

**System**
 - OS: windows server 2019
 - Coins: 1.12.2
 - mythicMobs: 5.0.1
 - Paper mc: git-Paper-220 (MC: 1.18.2)

**Error**
```
[15:22:01 INFO]: [Coins] Enabling Coins v1.12.2
[15:22:01 INFO]: [Coins] Vault is used as the economy provider.
[15:22:01 ERROR]: Error occurred while enabling Coins v1.12.2 (Is it up to date?)
java.lang.NoClassDefFoundError: io/lumine/xikage/mythicmobs/drops/Drop
        at me.justeli.coins.Coins.registerEvents(Coins.java:220) ~[Coins-1.12.2.jar:?]
        at me.justeli.coins.Coins.onEnable(Coins.java:99) ~[Coins-1.12.2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-247]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-247]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664) ~[paper-1.18.2.jar:git-Paper-247]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.18.2.jar:git-Paper-247]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-247]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-247]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-247]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: io.lumine.xikage.mythicmobs.drops.Drop
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 13 more
[15:22:01 INFO]: [Coins] Disabling Coins v1.12.2
```

**Additional context**
tried set "disable-mythic-mob-handling: true", no changes, same error.

**Comment by JustEli** [comment]
MythicMobs has released 5.x a while ago, we are trying to figure out how to add support for their new version. It's not easy because it's built on another Java version that we do not support. We are thinking of releasing an extra plugin just for MythicMobs support, but it may take a bit of time. Thanks for your patience.

**Comment by JustEli** [comment]
[Coins-b1.12.3.zip](https://github.com/JustEli/Coins/files/8403364/Coins-b1.12.3.zip)
I think I got it working, please let me know if Coins works with MM 5 now!
